### ISSUE TITLE
Annotations and Panel Errors

### ISSUE THREAD

**Issue by hansnolte** [atticus-lv/super_io#17]
Hi atticus-lv,

great Addon.

The Addon works in Blender 3.1 and 3.2, but I have error messages in the System console that delay the Blender start 

'bpy_prop_collection_idprop' object has no attribute '__annotations__'
Error: Registering panel class: 'SPIO_PT_ListFilterPanel' has category 'Tool'

Win 10 - 21H2
SPIO  1.36

EDIT:
I just deactivated it and get more error messages.

`E:\Blender\scripts\addons\super_io\preferences.py:694 Exception in module unregister(): 
'E:\\Blender\\scripts\\addons\\super_io\\__init__.py' Traceback (most recent call last):
 File "E:\Blender\3.2\scripts\modules\addon_utils.py", line 439, in disable mod.unregister()
  File "E:\Blender\scripts\addons\super_io\__init__.py", line 71, in unregister sys.modules[name].unregister()
  File "E:\Blender\scripts\addons\super_io\ui\ui_panel.py", line 165, in unregister bpy.utils.unregister_class(SPIO_PT_ListFilterPanel)
RuntimeError: unregister_class(...):, missing bl_rna attribute from 'RNAMeta' instance (may not be registered)`

**Comment by atticus-lv** [comment]
Yes, I noticed that the filter panel on the first row was lost in the 3.1. I will fix it after the Spring Festival Holiday
![image](https://user-images.githubusercontent.com/64118610/152213608-62e01f7e-cf54-4b9e-9b56-0e85f7240f98.png)

**Comment by atticus-lv** [comment]
fix in f194c231e2cc690bbf1759331a01f99fdc4cc284
